package net.alloyggp.escaperope;

import java.util.ArrayList;
import java.util.List;

//Quotes the string, turning quotes inside into double-quotes.
//Unescaping recognizes an unescaped comma as a control character.
public class CsvFieldEscaper implements Escaper {

    private CsvFieldEscaper() {
        //Use create() instead
    }

    public static Escaper create() {
        return new CsvFieldEscaper();
    }

    @Override
    public String escape(String input) {
        StringBuilder sb = new StringBuilder();
        sb.append('"');
        sb.append(input.replaceAll("\"", "\"\""));
        sb.append('"');
        return sb.toString();
    }

    @Override
    public List<UnescapeResult> unescape(String input) {
        List<UnescapeResult> results = new ArrayList<>();
        boolean insideQuotes = false;
        StringBuilder currentString = new StringBuilder();
        for (int i = 0; i < input.length(); /* incremented manually */) {
            int codePoint = input.codePointAt(i);

            if (codePoint == '"') {
                if (insideQuotes) {
                    if (i < input.length() - 1 && input.codePointAt(i+1) == '"') {
                        currentString.append('"');
                        i++;
                    } else {
                        insideQuotes = false;
                        results.add(UnescapeTextResult.create(currentString.toString()));
                        currentString = new StringBuilder();
                    }
                } else {
                    insideQuotes = true;
                }
            } else if (codePoint == ',' && !insideQuotes) {
                results.add(UnescapeControlResult.create(','));
            } else if (!insideQuotes) {
                throw new IllegalArgumentException("This wasn't generated by the CsvFieldEscaper or CsvLineDelimiter, so we don't know how to deal with it");
            } else {
                currentString.appendCodePoint(codePoint);
            }

            i += Character.charCount(codePoint);
        }
        return results;
    }

}
